gdb: fix build failure on aarch64
Commit 4da037ef9db (AArch64 SVE: Check for vector length change when
getting gdbarch) introduced a build failure:
../../gdb/aarch64-tdep.c: In function 'gdbarch* aarch64_gdbarch_init(gdbarch_info, gdbarch_list*)':
../../gdb/aarch64-tdep.c:3213:43: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
     internal_error (__FILE__, __LINE__, _("VQ out of bounds: %ld (max %d)"),
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~